# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4d5e25fc-322d-4993-99f5-85e7e299a184";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4d5e25fc-322d-4993-99f5-85e7e299a184";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/4d5e25fc-322d-4993-99f5-85e7e299a184";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/4d5e25fc-322d-4993-99f5-85e7e299a184";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/4d5e25fc-322d-4993-99f5-85e7e299a184";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/var/lib/containers" =
    { device = "/dev/disk/by-uuid/4d5e25fc-322d-4993-99f5-85e7e299a184";
      fsType = "btrfs";
      options = [ "subvol=@containers" ];
    };

  fileSystems."/var/libvirt" =
    { device = "/dev/disk/by-uuid/4d5e25fc-322d-4993-99f5-85e7e299a184";
      fsType = "btrfs";
      options = [ "subvol=@libvirt" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/4d5e25fc-322d-4993-99f5-85e7e299a184";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/4d5e25fc-322d-4993-99f5-85e7e299a184";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/4d5e25fc-322d-4993-99f5-85e7e299a184";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AF09-FA74";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/RAG-DATA" =
    { device = "/dev/disk/by-uuid/ec9d75cd-877d-4f66-9a6b-cfe7eb5ca9f0";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5ccb5cb3-75b1-4e05-918e-5000bed16da3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
