# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9d31dd94-2893-4c2a-bc47-bb2c4a8d55fc";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/9d31dd94-2893-4c2a-bc47-bb2c4a8d55fc";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/9d31dd94-2893-4c2a-bc47-bb2c4a8d55fc";
    fsType = "btrfs";
    options = [ "subvol=@log" ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/9d31dd94-2893-4c2a-bc47-bb2c4a8d55fc";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/9d31dd94-2893-4c2a-bc47-bb2c4a8d55fc";
    fsType = "btrfs";
    options = [ "subvol=@persist" ];
  };

  fileSystems."/RAG-DATA" = {
    device = "/dev/disk/by-uuid/ec9d75cd-877d-4f66-9a6b-cfe7eb5ca9f0";
    fsType = "btrfs";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a8b6794b-b034-44e6-8cd7-ef4013cb7fdd";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/9d31dd94-2893-4c2a-bc47-bb2c4a8d55fc";
    fsType = "btrfs";
    options = [ "subvol=@tmp" ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/9d31dd94-2893-4c2a-bc47-bb2c4a8d55fc";
    fsType = "btrfs";
    options = [ "subvol=@cache" ];
  };

  fileSystems."/var/lib/containers" = {
    device = "/dev/disk/by-uuid/9d31dd94-2893-4c2a-bc47-bb2c4a8d55fc";
    fsType = "btrfs";
    options = [ "subvol=@containers" ];
  };

  fileSystems."/var/lib/libvirt" = {
    device = "/dev/disk/by-uuid/9d31dd94-2893-4c2a-bc47-bb2c4a8d55fc";
    fsType = "btrfs";
    options = [ "subvol=@libvirt" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4509-A31C";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/8b6df5d3-9f96-4b48-8877-36bbe2642d21"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
