# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/27de4353-1342-4b35-b8a1-5e3ecc4dceea";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" "noatime" "ssd" "discard=async" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/27de4353-1342-4b35-b8a1-5e3ecc4dceea";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" "noatime" "ssd" "discard=async" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/27de4353-1342-4b35-b8a1-5e3ecc4dceea";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:3" "noatime" "ssd" "discard=async" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/27de4353-1342-4b35-b8a1-5e3ecc4dceea";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd:3" "noatime" "ssd" "discard=async" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/27de4353-1342-4b35-b8a1-5e3ecc4dceea";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "compress=zstd:3" "noatime" "ssd" "discard=async" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/var/lib/kryonix" =
    { device = "/dev/disk/by-uuid/f992fb1b-9855-4e58-9012-f22a3a4ccff7";
      fsType = "btrfs";
      options = [ "subvol=@kryonix" "compress=zstd:3" "noatime" "ssd" "discard=async" "nofail" "x-systemd.device-timeout=10s" ];
    };

  fileSystems."/srv/ragenterprise" =
    { device = "/dev/disk/by-uuid/f992fb1b-9855-4e58-9012-f22a3a4ccff7";
      fsType = "btrfs";
      options = [ "subvol=@ragenterprise" "compress=zstd:3" "noatime" "ssd" "discard=async" "nofail" "x-systemd.device-timeout=10s" ];
    };

  fileSystems."/srv/ragenterprise/vms" =
    { device = "/dev/disk/by-uuid/f992fb1b-9855-4e58-9012-f22a3a4ccff7";
      fsType = "btrfs";
      options = [ "subvol=@vms" "compress=zstd:3" "noatime" "ssd" "discard=async" "nofail" "x-systemd.device-timeout=10s" ];
    };

  fileSystems."/srv/ragenterprise/backups" =
    { device = "/dev/disk/by-uuid/f992fb1b-9855-4e58-9012-f22a3a4ccff7";
      fsType = "btrfs";
      options = [ "subvol=@backups" "compress=zstd:3" "noatime" "ssd" "discard=async" "nofail" "x-systemd.device-timeout=10s" ];
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
